<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lyfes_template"
 *
 * Auto generated by Extension Builder 2018-05-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'lyfes Template',
    'description' => 'Template Extension für lyfes Website',
    'category' => 'templates',
    'author' => 'JFR',
    'author_email' => 'jens.friederich@googlemail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
